### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by fmmattioni** [gadenbuie/shinyThings#4]
Hey @gadenbuie! Thanks a lot for this amazing package! It is quite handy!

Maybe I am working too late in the evening already, but I was trying to understand how the pagination functions work. Through the example provided, I do not seem to find a way to retrieve the current page. Like, I would like to render different things for page 1, page 2, and so on...

Any ideas?

Thanks in advance!
Felipe

**Comment by gadenbuie** [comment]
Hey Felipe! The idea behind the pagination module is to help avoid needing to worry about which page you're on currently. The output of the pagination module is the indexes of the things you want to show on the page.

So if you want to paginate the `letters` of the alphabet, with 10 letters on each "page", you'd create a pager module like this:

```r
page_indices <- shinyThings::pager("pager", n_items, page_break)
```

And then when you want to find out which items are in the currently selected "page" you call `page_indices()`:

```r
output$current_letters <- renderPrint({
  letters[page_indices()]
})
```

So on page 1 `page_indices()` returns `1, 2, ..., 10` and on page 2 it returns `11, 12, ... 20`.

Note that you do still need to create the output for the things shown on the page yourself, the pager only gives you the indices for the things on the current page.

If you want just one thing per page, you can set your `page_break` to `1`, and then the page indices are equivalent to the page number. Or you could use that to decide which page and render completely different content, the sky's the limit!

**Comment by fmmattioni** [comment]
Oh that was exactly what I needed! Thank you so much, @gadenbuie!

**Comment by gadenbuie** [comment]
Awesome! Glad that made sense and that this little package is helpful 😄

**Comment by fmmattioni** [comment]
I am sorry, one more thing: any ideas on how I could save the state of a page?

For example, in my app, if a button is clicked a `css` class is added to a `div` so it gets highlighted. But if I click "Next" and then come back to the previous page, it "refreshes" that page and that `css` class modification I did previously does not get saved.

Do you think I could somehow save the `div`, and then if I come back to it I replace it?

I hope that makes sense.
